#!/bin/sh

# the interpreter to run
prog="node"

USAGE='jsfs - shell filesystem
ipfs-based filesystem whose files are the
result of executing javascript programs
'

cmd="$1"
shift

case "$cmd" in
cat) ipfs cat $@ | $prog ;;
add) ipfs add $@ ;;
*) die "$USAGE" ;;
esac
